# Generated by Django 5.2.6 on 2025-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="runner",
            name="name",
            field=models.CharField(default="pre-existing", max_length=255),
            preserve_default=False,
        ),
    ]
