# Generated by Django 5.2.6 on 2025-09-24 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datasets", "0004_rename_runner_datasetconfig_pipeline_and_more"),
        ("pipelines", "0002_runner_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Runner",
            new_name="Pipeline",
        ),
    ]
