# Generated by Django 5.2.6 on 2025-12-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pipelines", "0004_pipelineapikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pipelineapikey",
            name="deactivated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
