[workspace]
authors = ["Alex Kerney <abk@mac.com>"]
channels = ["conda-forge"]
name = "s3_timeseries"
platforms = ["linux-64", "linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
ioos_qc = ">=2.2.1,<3"
pandas = ">=2.3.2,<3"
pydantic = ">=2.11.9,<3"
httpx = ">=0.28.1,<0.29"
xarray = ">=2025.9.0,<2026"
netcdf4 = ">=1.7.2,<2"
sentry-sdk = ">=2.38.0,<3"
dagster = ">=1.11.11,<2"
s3fs = ">=2025.9.0,<2026"
parse = ">=1.20.2,<2"
dagster-k8s = ">=1!0.27.11,<1!0.28"
dagster-postgres = ">=1!0.27.11,<1!0.28"
dagster-aws = ">=1!0.27.11,<1!0.28"
