name: Core

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_backend:
    name: Build backend Python Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

    - name: Build Backend
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ./backend
        push: false
        tags: gmri/buoy_retriever_backend:latest

  build_frontend:
    name: Build Next.js frontend Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

    - name: Build Frontend
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ./frontend
        push: false
        tags: gmri/buoy_retriever_frontend:latest
        build-args: |
          NEXT_PUBLIC_BACKEND_URL=https://oso.ioos.us
          NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}

  test_common:
    name: Test common package
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      matrix:
        python-version:
          - "3.13"
          # - "3.14"

    steps:
    - name: Checkout
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

    - name: Set up Python
      uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e # v6
      with:
        working-directory: ./common
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      working-directory: ./common
      run: |
        uv run pytest -vv --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe # v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        flags: common

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@0fa95f0e1eeaafde2c782583b36b28ad0d8c77d3 # v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
